const APP_VERSION='2.3.1';
const STORAGE_KEY='dwdmFieldCalcHistoryV2';
const SETTINGS={capacity:40,fiberAttenuation:.30,targetOk:.50,targetReview:1.50,lossOk:.50,lossReview:1.50};
const MODELS=[
 {id:'boa21',name:'BOA21',stage:'Booster',roles:['tx'],pout:21,gmin:20,gmax:20,manualMin:10,manualMax:27,source:'Planilha Padtec V1.2'},
 {id:'boa24',name:'BOA24',stage:'Booster',roles:['tx'],pout:24,gmin:23,gmax:23,manualMin:10,manualMax:27,source:'Planilha Padtec V1.2'},
 {id:'eoa18gw',name:'EOA 18 GW',stage:'Alto ganho',roles:['tx','rx'],pout:18,gmin:15,gmax:22,manualMin:10,manualMax:27,pinMin:-32,pinMax:8,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'eoa18lw',name:'EOA 18 LW',stage:'Baixo ganho',roles:['tx','rx'],pout:18,gmin:15,gmax:17,manualMin:5,manualMax:20,pinMin:-25,pinMax:13,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'eoa18z1',name:'EOA 18 ZW · Estágio RX',stage:'Alto ganho',roles:['rx'],pout:18,gmin:15,gmax:22,manualMin:10,manualMax:27,pinMin:-32,pinMax:8,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'eoa18z2',name:'EOA 18 ZW · Estágio TX',stage:'Baixo ganho',roles:['tx'],pout:18,gmin:15,gmax:17,manualMin:5,manualMax:20,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'eoa21gw',name:'EOA 21 GW',stage:'Alto ganho',roles:['tx','rx'],pout:20,gmin:18,gmax:22,manualMin:10,manualMax:27,pinMin:-35,pinMax:11,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'eoa21z1',name:'EOA 21 ZW · Estágio RX',stage:'Alto ganho',roles:['rx'],pout:20,gmin:18,gmax:22,manualMin:10,manualMax:27,pinMin:-35,pinMax:11,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'eoa21z2',name:'EOA 21 ZW · Estágio TX',stage:'Baixo ganho · provisório',roles:['tx'],pout:20,gmin:17,gmax:18,manualMin:5,manualMax:20,source:'Planilha Padtec V1.2',trusted:false,warning:'EOA 21 ZW TX: a planilha Padtec apresenta dados divergentes para este estágio. O resultado não deve ser usado para ajuste definitivo sem validar o código exato do equipamento.'},
 {id:'hoa1',name:'HOA · Estágio 1 (Híbrido RX)',stage:'Híbrido / recepção',roles:['rx'],pout:20,gmin:25,gmax:34,manualMin:20,manualMax:38,pinMin:-43,pinMax:0,source:'Planilha Padtec V1.2 + Manual TM.LP64'},
 {id:'hoa2',name:'HOA · Estágio 2 (EDFA TX)',stage:'EDFA / transmissão',roles:['tx'],pout:20,gmin:18,gmax:22,manualMin:10,manualMax:28,source:'Planilha Padtec V1.2 + Manual TM.LP64'}
];
const $=id=>document.getElementById(id);
const parseLocale=value=>{const raw=String(value??'').trim().replace(/\s/g,'').replace(',','.');return raw===''?null:Number.isFinite(Number(raw))?Number(raw):null};
const value=id=>parseLocale($(id).value);
const fmt=(v,d=1,sign=false)=>v==null||!Number.isFinite(v)?'—':`${sign&&v>0?'+':''}${v.toFixed(d).replace('.',',')}`;
const escapeHtml=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const todayLocal=()=>{const d=new Date(),offset=d.getTimezoneOffset()*60000;return new Date(d-offset).toISOString().slice(0,10)};
const formatDate=value=>{if(!value)return'Não informada';const [y,m,d]=value.split('-');return y&&m&&d?`${d}/${m}/${y}`:value};
const filenamePart=value=>String(value||'Trecho_sem_identificacao').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,80)||'Trecho_sem_identificacao';
let mode='Ativação',current=null;

function modelById(id){return MODELS.find(m=>m.id===id)}
function selectedModel(role){return modelById($(role==='tx'?'txModel':'rxModel').value)}
function fillModels(){for(const role of ['tx','rx']){const select=$(role+'Model');select.innerHTML='';MODELS.filter(m=>m.roles.includes(role)).forEach(m=>{const o=document.createElement('option');o.value=m.id;o.textContent=m.name+(m.trusted===false?' ⚠':'');select.append(o)});select.value='eoa18gw'}}
function spec(el,m){el.innerHTML=`<span>Pout ref. 40 canais: ${fmt(m.pout)} dBm</span><span>Faixa operacional: ${fmt(m.gmin)}–${fmt(m.gmax)} dB</span><span>Faixa física manual: ${fmt(m.manualMin)}–${fmt(m.manualMax)} dB</span>${m.pinMin!=null?`<span>Entrada física: ${fmt(m.pinMin,0,true)} a ${fmt(m.pinMax,0,true)} dBm</span>`:''}<span>${m.stage}</span><span>Fonte: ${m.source}</span>`}
function setDot(el,state){el.className=el.classList.contains('status-dot')?'status-dot':'mini-dot';el.classList.add(state)}
function inRange(v,min,max){return v!=null&&v>=min&&v<=max}
function statusClass(s){return s==='OK'?'text-ok':s==='Atenção'?'text-warn':s==='Pendente'?'':'text-bad'}
function severityFromDelta(delta,ok=SETTINGS.targetOk,review=SETTINGS.targetReview){const a=Math.abs(delta);return a<=ok?'ok':a<=review?'attention':'review'}
function targetStatus(el,v,target){if(v==null||target==null){el.textContent='medição não informada';el.className='';return null}const delta=v-target,level=severityFromDelta(delta),word=delta>0?'acima':'abaixo';el.textContent=level==='ok'?`medido ${fmt(v,2,true)} dBm · dentro de ±${fmt(SETTINGS.targetOk,2)} dB`:`medido ${fmt(v,2,true)} dBm · ${fmt(Math.abs(delta),2)} dB ${word}`;el.className=level==='ok'?'text-ok':level==='attention'?'text-warn':'text-bad';return level}
function rangeStatus(el,v,min,max){if(v==null||min==null||max==null){el.textContent='medição não informada';el.className='';return null}const ok=inRange(v,min,max);if(ok)el.textContent=`medido ${fmt(v,2,true)} dBm · dentro da faixa`;else{const above=v>max,delta=above?v-max:min-v;el.textContent=`medido ${fmt(v,2,true)} dBm · ${fmt(delta,2)} dB ${above?'acima':'abaixo'} da faixa`}el.className=ok?'text-ok':'text-bad';return ok?'ok':'review'}
function lineInStatus(el,v,predicted,rx,targetOut){if(v==null||predicted==null||targetOut==null){el.textContent='medição não informada';el.className='';return null}const physicalOk=rx.pinMin==null||inRange(v,rx.pinMin,rx.pinMax),required=targetOut-v,gainOk=inRange(required,rx.gmin,rx.gmax),delta=v-predicted;if(!physicalOk){const above=v>rx.pinMax,d=above?v-rx.pinMax:rx.pinMin-v;el.textContent=`medido ${fmt(v,2,true)} dBm · ${fmt(d,2)} dB ${above?'acima':'abaixo'} do limite físico`;el.className='text-bad';return'review'}if(!gainOk){el.textContent=`medido ${fmt(v,2,true)} dBm · exigiria ganho ${fmt(required,2)} dB`;el.className='text-bad';return'review'}if(delta>SETTINGS.targetOk){el.textContent=`medido ${fmt(v,2,true)} dBm · ${fmt(delta,2)} dB acima da previsão conservadora`;el.className='text-ok';return'ok'}const level=severityFromDelta(delta);el.textContent=level==='ok'?`medido ${fmt(v,2,true)} dBm · compatível`:`medido ${fmt(v,2,true)} dBm · ${fmt(Math.abs(delta),2)} dB abaixo da previsão`;el.className=level==='attention'?'text-warn':level==='review'?'text-bad':'text-ok';return level}
function renderFiberDirection(cardId,lossId,deltaId,rateId,loss,expected,distance){const card=$(cardId),lossEl=$(lossId),deltaEl=$(deltaId),rateEl=$(rateId);if(loss==null||expected==null){card.className='';lossEl.textContent='Aguardando medições';deltaEl.textContent='Informe TX OUT e RX IN';rateEl.textContent='—';return null}const delta=loss-expected,rate=distance>0?loss/distance:null,level=loss<0?'critical':delta<=SETTINGS.lossOk?'good':delta<=SETTINGS.lossReview?'attention':'critical';card.className=level;lossEl.textContent=`${fmt(loss,2)} dB`;if(loss<0)deltaEl.textContent='Valor inválido: perda negativa';else if(delta<0)deltaEl.textContent=`${fmt(Math.abs(delta),2)} dB de margem favorável`;else if(delta<=SETTINGS.lossOk)deltaEl.textContent=`${fmt(delta,2)} dB acima · compatível`;else deltaEl.textContent=`${fmt(delta,2)} dB acima da referência`;rateEl.textContent=rate==null?'—':`${fmt(rate,3)} dB/km`;return{loss,delta,rate,level}}
function issue(level,title,detail,action){return{level,title,detail,action}}
function renderDiagnostics(issues,status,measurementsComplete){const el=$('diagnosticSummary');if(status==='OK'){el.innerHTML=measurementsComplete?'<div class="diag-ok"><strong>Trecho conforme</strong><p>Ganhos e potências estão dentro das referências operacionais informadas.</p></div>':'<div class="diag-ok"><strong>Referência de ativação calculada</strong><p>A combinação teórica é possível. Insira medições para validar o comportamento real.</p></div>';el.className='diagnostic-summary text-ok';return}const order={review:0,attention:1,pending:2};issues.sort((a,b)=>order[a.level]-order[b.level]);el.innerHTML=`<div class="diag-list">${issues.map(i=>`<article class="diag-item ${i.level==='review'?'critical':i.level}"><div><span>${i.level==='review'?'CRÍTICO':i.level==='attention'?'ATENÇÃO':'PENDENTE'}</span><strong>${escapeHtml(i.title)}</strong></div><p>${escapeHtml(i.detail)}</p><small><b>Ação:</b> ${escapeHtml(i.action)}</small></article>`).join('')}</div>`;el.className='diagnostic-summary'}
function calculate(){
 const rawChannels=value('channels'),channelValid=Number.isInteger(rawChannels)&&rawChannels>=1&&rawChannels<=SETTINGS.capacity,ch=channelValid?rawChannels:null,distance=value('distance'),distanceValid=distance!=null&&distance>0;
 $('channelsError').textContent=channelValid?'':'Informe um número inteiro entre 1 e 40.';$('distanceError').textContent=distanceValid?'':'Informe uma distância maior que zero.';
 const tx=selectedModel('tx'),rx=selectedModel('rx');spec($('txSpec'),tx);spec($('rxSpec'),rx);
 const reduction=ch?10*Math.log10(SETTINGS.capacity/ch):null,txOut=ch?tx.pout-reduction:null,rxOut=ch?rx.pout-reduction:null,expectedLoss=distanceValid?distance*SETTINGS.fiberAttenuation:null,lineIn=txOut!=null&&expectedLoss!=null?txOut-expectedLoss:null,txInMin=txOut!=null?txOut-tx.gmax:null,txInMax=txOut!=null?txOut-tx.gmin:null,rxRequired=rxOut!=null&&lineIn!=null?rxOut-lineIn:null;
 const mdi=value('mDataIn'),mRxInA=value('mRxInA'),mlo=value('mLineOut'),mli=value('mLineIn'),mTxOutB=value('mTxOutB'),mdo=value('mDataOut'),channelFactor=ch?10*Math.log10(ch):null,txGain=mdi!=null&&mlo!=null?mlo-mdi:null,rxGain=mli!=null&&mdo!=null?mdo-mli:null,actualLoss=mlo!=null&&mli!=null?mlo-mli:null,effectiveAtt=actualLoss!=null&&distanceValid?actualLoss/distance:null,lossDelta=actualLoss!=null&&expectedLoss!=null?actualLoss-expectedLoss:null,actualLossBA=mTxOutB!=null&&mRxInA!=null?mTxOutB-mRxInA:null,effectiveAttBA=actualLossBA!=null&&distanceValid?actualLossBA/distance:null,lossDeltaBA=actualLossBA!=null&&expectedLoss!=null?actualLossBA-expectedLoss:null,txDev=mlo!=null&&txOut!=null?mlo-txOut:null,rxDev=mdo!=null&&rxOut!=null?mdo-rxOut:null,lineInDev=mli!=null&&lineIn!=null?mli-lineIn:null;
 const txGainOk=txGain==null?null:inRange(txGain,tx.gmin,tx.gmax),rxGainOk=rxGain==null?null:inRange(rxGain,rx.gmin,rx.gmax),rxRequiredOk=rxRequired==null?null:inRange(rxRequired,rx.gmin,rx.gmax);
 rangeStatus($('sDataIn'),mdi,txInMin,txInMax);targetStatus($('sLineOut'),mlo,txOut);lineInStatus($('sLineIn'),mli,lineIn,rx,rxOut);targetStatus($('sDataOut'),mdo,rxOut);
 const complete=[mdi,mlo,mli,mdo].every(v=>v!=null),measurementsRequired=mode==='Revisão',issues=[];
 if(!channelValid)issues.push(issue('pending','Quantidade de canais inválida','O cálculo depende da quantidade ativa de canais.','Informe de 1 a 40 canais, sem casas decimais.'));
 if(!distanceValid)issues.push(issue('pending','Distância inválida','A distância deve ser maior que zero.','Informe a distância óptica do trecho em quilômetros.'));
 if(measurementsRequired&&!complete)issues.push(issue('pending','Medições incompletas','Na revisão são necessárias DATA IN A, LINE OUT A, LINE IN B e DATA OUT B.','Preencha as quatro potências totais para concluir.'));
 if(mdi!=null&&txInMin!=null&&!inRange(mdi,txInMin,txInMax)){const above=mdi>txInMax,d=above?mdi-txInMax:txInMin-mdi;issues.push(issue('review','DATA IN do TX fora da faixa',`Esperado ${fmt(txInMin,2,true)} a ${fmt(txInMax,2,true)} dBm; medido ${fmt(mdi,2,true)} dBm (${fmt(d,2)} dB ${above?'acima':'abaixo'}).`,'Verifique a potência anterior, o VOA e o plano de potência antes de alterar o ganho.'))}
 if(rxRequiredOk===false)issues.push(issue('review','Ganho teórico do RX insuficiente',`O trecho exigiria ${fmt(rxRequired,2)} dB; a faixa operacional é ${fmt(rx.gmin)} a ${fmt(rx.gmax)} dB.`,'Revise o modelo do RX, a perda do trecho ou a arquitetura de amplificação.'));
 if(mli!=null&&rx.pinMin!=null&&!inRange(mli,rx.pinMin,rx.pinMax)){const above=mli>rx.pinMax,d=above?mli-rx.pinMax:rx.pinMin-mli;issues.push(issue('review','LINE IN fora do limite físico do RX',`Faixa física ${fmt(rx.pinMin,0,true)} a ${fmt(rx.pinMax,0,true)} dBm; medido ${fmt(mli,2,true)} dBm (${fmt(d,2)} dB ${above?'acima':'abaixo'}).`,'Verifique o nível recebido e não aplique ajuste antes de confirmar o limite do equipamento.'))}
 const rxGainForMeasuredInput=mli!=null&&rxOut!=null?rxOut-mli:null;if(rxGainForMeasuredInput!=null&&!inRange(rxGainForMeasuredInput,rx.gmin,rx.gmax))issues.push(issue('review','LINE IN incompatível com o alvo do RX',`Com LINE IN ${fmt(mli,2,true)} dBm, seriam necessários ${fmt(rxGainForMeasuredInput,2)} dB para atingir ${fmt(rxOut,2,true)} dBm; a faixa operacional é ${fmt(rx.gmin)} a ${fmt(rx.gmax)} dB.`,'Revise o modelo, o ganho/VOA ou o alvo de saída antes do ajuste.'));
 if(txGainOk===false)issues.push(issue('review','Ganho TX fora da faixa',`Medido ${fmt(txGain,2)} dB; permitido ${fmt(tx.gmin)} a ${fmt(tx.gmax)} dB.`,'Confira DATA IN/LINE OUT, AGC e VOA do estágio TX.'));
 if(rxGainOk===false)issues.push(issue('review','Ganho RX fora da faixa',`Medido ${fmt(rxGain,2)} dB; permitido ${fmt(rx.gmin)} a ${fmt(rx.gmax)} dB.`,'Confira LINE IN/DATA OUT, AGC e VOA do estágio RX.'));
 if(actualLoss!=null&&actualLoss<0)issues.push(issue('review','Ganho inesperado entre os pontos','LINE IN B ficou maior que LINE OUT A, resultando em perda negativa.','Confira o sentido das medições ou modele separadamente eventual amplificação intermediária/Raman.'));
 else if(lossDelta!=null){const level=lossDelta<=SETTINGS.lossOk?'ok':lossDelta<=SETTINGS.lossReview?'attention':'review';if(level!=='ok')issues.push(issue(level,'Perda total acima da referência simplificada',`Referência da fibra ${fmt(expectedLoss,2)} dB; perda total medida ${fmt(actualLoss,2)} dB; diferença ${fmt(lossDelta,2,true)} dB.`,'Considere conectores, DIO, MUX/DEMUX, filtros e demais passivos entre LINE OUT e LINE IN.'))}
 if(actualLossBA!=null&&actualLossBA<0)issues.push(issue('review','Ganho inesperado no sentido B → A','RX IN A ficou maior que TX OUT B, resultando em perda negativa.','Confira o sentido e os pontos das medições do caminho B → A.'))
 else if(lossDeltaBA!=null&&lossDeltaBA>SETTINGS.lossOk){const level=lossDeltaBA<=SETTINGS.lossReview?'attention':'review';issues.push(issue(level,'Perda B → A acima da referência simplificada',`Referência da fibra ${fmt(expectedLoss,2)} dB; perda medida ${fmt(actualLossBA,2)} dB; diferença ${fmt(lossDeltaBA,2,true)} dB.`,'Considere conectores, DIO, MUX/DEMUX, filtros e demais passivos do sentido B → A.'))}
 if(txDev!=null&&Math.abs(txDev)>SETTINGS.targetOk)issues.push(issue(severityFromDelta(txDev),'LINE OUT diferente do alvo',`Alvo ${fmt(txOut,2,true)} dBm; medido ${fmt(mlo,2,true)} dBm; desvio ${fmt(txDev,2,true)} dB.`,'Verifique carregamento, AGC e potência de entrada do TX.'));
 if(rxDev!=null&&Math.abs(rxDev)>SETTINGS.targetOk)issues.push(issue(severityFromDelta(rxDev),'DATA OUT diferente do alvo',`Alvo ${fmt(rxOut,2,true)} dBm; medido ${fmt(mdo,2,true)} dBm; desvio ${fmt(rxDev,2,true)} dB.`,'Verifique ganho, AGC, VOA e saturação do estágio RX.'));
 if(tx.trusted===false||rx.trusted===false)issues.push(issue('review','Modelo com referência provisória','Há divergência na fonte de implantação para o estágio selecionado.','Confirme o código completo e os parâmetros na documentação vigente.'));
 const hasReview=issues.some(i=>i.level==='review'),hasAttention=issues.some(i=>i.level==='attention'),hasPending=issues.some(i=>i.level==='pending'),status=hasPending?'Pendente':hasReview?'Revisar':hasAttention?'Atenção':'OK';
 $('channelCount').textContent=ch??'—';$('loadingMargin').textContent=reduction==null?'—':`${fmt(reduction,2)} dB`;$('totalLoss').textContent=expectedLoss==null?'—':`${fmt(expectedLoss,2)} dB`;$('lossBreakdown').textContent=distanceValid?`${fmt(distance,1)} km × 0,30 dB/km`:'aguardando distância';$('dataInRange').textContent=txInMin==null?'—':`${fmt(txInMin,1,true)} a ${fmt(txInMax,1,true)}`;$('lineOutTarget').textContent=fmt(txOut,1,true);$('lineInTarget').textContent=fmt(lineIn,1,true);$('dataOutTarget').textContent=fmt(rxOut,1,true);$('fiberLabel').textContent=expectedLoss==null?'distância pendente':`${fmt(distance,1)} km · −${fmt(expectedLoss,1)} dB`;
 $('txGainRange').textContent=`${fmt(tx.gmin)} a ${fmt(tx.gmax)} dB`;$('rxGainRange').textContent=`${fmt(rx.gmin)} a ${fmt(rx.gmax)} dB`;$('txGainRequired').textContent=txGain==null?'aguardando medições':`${fmt(txGain,2)} dB`;$('rxGainRequired').textContent=rxRequired==null?'—':`${fmt(rxRequired,2)} dB`;$('rxGainFromMeasured').textContent=mli!=null&&rxOut!=null?`${fmt(rxOut-mli,2)} dB`:'aguardando LINE IN';$('rxGainMeasured').textContent=rxGain==null?'aguardando medições':`${fmt(rxGain,2)} dB`;
 const txPer=tx.pout-10*Math.log10(SETTINGS.capacity),rxPer=rx.pout-10*Math.log10(SETTINGS.capacity),txMeasuredPer=mlo!=null&&channelFactor!=null?mlo-channelFactor:null,rxMeasuredPer=mdo!=null&&channelFactor!=null?mdo-channelFactor:null,estimateCapacity=(pout,per)=>per==null?null:Math.max(0,Math.min(SETTINGS.capacity,Math.floor(10**((pout-per)/10)))),txSupported=estimateCapacity(tx.pout,txMeasuredPer),rxSupported=estimateCapacity(rx.pout,rxMeasuredPer),spanSupported=txSupported==null||rxSupported==null?null:Math.min(txSupported,rxSupported);
 $('txPerChannel').textContent=`${fmt(txPer,2,true)} dBm`;$('rxPerChannel').textContent=`${fmt(rxPer,2,true)} dBm`;$('txPerChannelMeasured').textContent=txMeasuredPer==null?'aguardando LINE OUT':`${fmt(txMeasuredPer,2,true)} dBm`;$('rxPerChannelMeasured').textContent=rxMeasuredPer==null?'aguardando DATA OUT':`${fmt(rxMeasuredPer,2,true)} dBm`;$('txSupported').textContent=txSupported==null?'—':`${txSupported} canais`;$('rxSupported').textContent=rxSupported==null?'—':`${rxSupported} canais`;$('spanSupported').textContent=spanSupported==null?'Aguardando medições':`${spanSupported} de 40 canais`;$('capacityState').className=`capacity-summary ${spanSupported==null?'':spanSupported>=SETTINGS.capacity?'good':spanSupported>=ch?'attention':'critical'}`;$('capacityHint').textContent=spanSupported==null?'Informe LINE OUT A e DATA OUT B.':spanSupported>=SETTINGS.capacity?'Potência medida compatível com até 40 canais.':spanSupported>=ch?`Suporta os ${ch} canais atuais, mas não 40 neste nível médio.`:`A estimativa é menor que os ${ch} canais informados; revise as medições e o equilíbrio espectral.`;setDot($('txCheckDot'),txGainOk==null?'review':txGainOk?'ok':'bad');setDot($('rxCheckDot'),rxGainOk==null?'review':rxGainOk?'ok':'bad');
 $('actualSpanLoss').textContent=actualLoss==null?'Aguardando medições':`${fmt(actualLoss,2)} dB`;$('effectiveAttenuation').textContent=effectiveAtt==null?'—':`${fmt(effectiveAtt,3)} dB/km`;
 if(lossDelta==null){$('excessLoss').textContent='—';$('spanLossStatus').textContent='Informe LINE OUT A e LINE IN B';$('excessLossStatus').textContent='Referência simplificada: distância × 0,30';$('spanLossCard').className=''}else{const favorable=lossDelta<0,level=actualLoss<0?'review':lossDelta<=SETTINGS.lossOk?'ok':lossDelta<=SETTINGS.lossReview?'attention':'review';$('excessLoss').textContent=favorable?`+${fmt(Math.abs(lossDelta),2)} dB de margem`:`${fmt(lossDelta,2)} dB acima`;$('spanLossStatus').textContent=level==='ok'?(favorable?'PERDA COMPATÍVEL · balanço favorável':'PERDA COMPATÍVEL · dentro da referência'):level==='attention'?'ATENÇÃO · considere perdas passivas':actualLoss<0?'REVISAR · perda negativa':'REVISAR · perda elevada no trecho';$('spanLossStatus').className=level==='ok'?'text-ok':level==='attention'?'text-warn':'text-bad';$('excessLossStatus').textContent=favorable?`Perda ${fmt(Math.abs(lossDelta),2)} dB menor que a referência conservadora`:`Fibra ref. ${fmt(expectedLoss,2)} dB · total medido ${fmt(actualLoss,2)} dB`;$('excessLossStatus').className=$('spanLossStatus').className;$('spanLossCard').className=`fiber-state ${level==='ok'?'good':level==='attention'?'attention':'critical'}`}
 $('outputDeviations').textContent=txDev==null&&rxDev==null?'—':`TX ${fmt(txDev,2,true)} · RX ${fmt(rxDev,2,true)} dB`;$('outputDeviationStatus').textContent='desvio medido em relação ao alvo';
 if(status==='OK'){setDot($('statusDot'),'ok');$('overallStatus').textContent=complete?'Trecho dentro das referências':'Referência de ativação calculada';$('actionText').textContent=complete?'Ganhos e potências compatíveis com as referências operacionais.':'Combinação teórica possível; as medições permanecem opcionais neste modo.'}else if(status==='Atenção'){setDot($('statusDot'),'review');$('overallStatus').textContent='Trecho requer atenção';$('actionText').textContent='Há desvio moderado; avalie os passivos e as medições antes do ajuste.'}else if(status==='Revisar'){setDot($('statusDot'),'bad');$('overallStatus').textContent='Revisar antes do ajuste';$('actionText').textContent='Há condição crítica ou equipamento fora da faixa operacional.'}else{setDot($('statusDot'),'review');$('overallStatus').textContent='Complete os dados do trecho';$('actionText').textContent='O resultado final será liberado após os dados obrigatórios.'}
 renderDiagnostics(issues,status,complete);const warnings=[tx.warning,rx.warning].filter(Boolean);$('modelWarning').hidden=!warnings.length;$('modelWarning').textContent=warnings.join(' ');const pointA=$('origin').value.trim()||'Ponto A',pointB=$('destination').value.trim()||'Ponto B';$('pointALabel').textContent=pointA;$('pointBLabel').textContent=pointB;$('fiberPointALabel').textContent=pointA;$('fiberPointBLabel').textContent=pointB;$('fiberABLabel').textContent=`${pointA} → ${pointB}`;$('fiberBALabel').textContent=`${pointB} → ${pointA}`;$('resultTitle').textContent=$('spanName').value.trim()||`${pointA} → ${pointB}`;renderFiberDirection('fiberABCard','fiberLossAB','fiberDeltaAB','fiberDbKmAB',actualLoss,expectedLoss,distance);renderFiberDirection('fiberBACard','fiberLossBA','fiberDeltaBA','fiberDbKmBA',actualLossBA,expectedLoss,distance);
 current={schema:2,appVersion:APP_VERSION,date:new Date().toISOString(),surveyDate:$('reportDate').value,mode,span:$('resultTitle').textContent,origin:pointA,destination:pointB,channels:ch,distance,txId:tx.id,tx:tx.name,rxId:rx.id,rx:rx.name,measurements:{dataInA:mdi,rxInA:mRxInA,lineOutA:mlo,lineInB:mli,txOutB:mTxOutB,dataOutB:mdo},expected:{loadingMargin:reduction,txOut,lineIn,rxOut,txInMin,txInMax,loss:expectedLoss,rxRequired},measured:{actualLoss,effectiveAtt,lossDelta,actualLossBA,effectiveAttBA,lossDeltaBA,actualTxGain:txGain,actualRxGain:rxGain,txPerChannel:txMeasuredPer,rxPerChannel:rxMeasuredPer,lineInDev,txDev,rxDev},supportedChannels:{tx:txSupported,rx:rxSupported,span:spanSupported},status,complete:channelValid&&distanceValid&&(!measurementsRequired||complete),measurementsComplete:complete,fiberMeasurementsComplete:[mRxInA,mlo,mli,mTxOutB].every(v=>v!=null),issues};$('saveBtn').disabled=!current.complete;
}
function history(){migrateLegacyHistory();try{const rows=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');return Array.isArray(rows)?rows:[]}catch{return[]}}
function store(rows){localStorage.setItem(STORAGE_KEY,JSON.stringify(rows.slice(0,100)))}
function migrateLegacyHistory(){if(localStorage.getItem(STORAGE_KEY))return;try{const old=JSON.parse(localStorage.getItem('dwdmFieldCalcHistory')||'[]');if(!Array.isArray(old)||!old.length)return;store(old.map(r=>({schema:2,appVersion:r.appVersion||'1.x',date:r.date,mode:r.mode,span:r.span,origin:'Ponto A',destination:'Ponto B',channels:r.channels,distance:r.distance,txId:null,tx:r.tx,rxId:null,rx:r.rx,measurements:{},expected:{loss:r.loss,txOut:r.txOut,lineIn:r.lineIn,rxRequired:r.rxRequired},measured:{actualLoss:r.actualLoss,effectiveAtt:r.effectiveAtt,lossDelta:r.lossDelta,actualTxGain:r.actualTxGain,actualRxGain:r.actualRxGain},supportedChannels:{},status:r.status,complete:false,measurementsComplete:false,issues:[],legacy:true})))}catch{}}
function renderHistory(){const rows=history(),table=$('historyTable'),empty=$('historyEmpty');table.hidden=!rows.length;empty.hidden=!!rows.length;table.querySelector('tbody').innerHTML=rows.map((r,i)=>`<tr><td>${new Date(r.date).toLocaleString('pt-BR')}</td><td>${escapeHtml(r.mode)}</td><td>${escapeHtml(r.span)}</td><td>${r.channels}/40</td><td>${fmt(r.distance)} km · ref. ${fmt(r.expected?.loss)} dB${r.measured?.actualLoss!=null?` / A→B ${fmt(r.measured.actualLoss)} dB`:''}${r.measured?.actualLossBA!=null?` / B→A ${fmt(r.measured.actualLossBA)} dB`:''}</td><td>${escapeHtml(r.tx)}</td><td>${escapeHtml(r.rx)}</td><td class="${statusClass(r.status)}">${escapeHtml(r.status)}</td><td class="row-actions"><button data-action="open" data-index="${i}" title="Reabrir">Abrir</button><button data-action="reverse" data-index="${i}" title="Duplicar no sentido inverso">Inverter</button><button class="delete-record" data-action="delete" data-index="${i}" title="Excluir">×</button></td></tr>`).join('')}
function save(){if(!current?.complete){$('saveFeedback').textContent='Complete os dados obrigatórios antes de salvar.';return}const rows=history();rows.unshift(structuredClone(current));store(rows);renderHistory();$('saveFeedback').textContent='Análise salva neste dispositivo.';setTimeout(()=>$('saveFeedback').textContent='',2200)}
function loadRecord(r,reverse=false){$('spanName').value=reverse?`${r.destination} → ${r.origin}`:r.span;$('origin').value=reverse?r.destination:r.origin;$('destination').value=reverse?r.origin:r.destination;$('reportDate').value=r.surveyDate||String(r.date||'').slice(0,10)||todayLocal();$('channels').value=r.channels;$('distance').value=fmt(r.distance,2);const txCandidate=reverse?r.rxId:r.txId,rxCandidate=reverse?r.txId:r.rxId;$('txModel').value=modelById(txCandidate)?.roles.includes('tx')?txCandidate:'eoa18gw';$('rxModel').value=modelById(rxCandidate)?.roles.includes('rx')?rxCandidate:'eoa18gw';const m=r.measurements||{},values=reverse?{mDataIn:null,mRxInA:m.lineInB,mLineOut:m.txOutB,mLineIn:m.rxInA,mTxOutB:m.lineOutA,mDataOut:null}:{mDataIn:m.dataInA,mRxInA:m.rxInA,mLineOut:m.lineOutA,mLineIn:m.lineInB,mTxOutB:m.txOutB,mDataOut:m.dataOutB};for(const [id,v] of Object.entries(values))$(id).value=v==null?'':fmt(v,2);calculate();window.scrollTo({top:0,behavior:'smooth'})}
function fiberReportState(loss,delta){if(loss==null||delta==null)return{label:'Pendente',className:''};if(loss<0)return{label:'Revisar: perda negativa',className:'critical'};if(delta<0)return{label:`Boa · ${fmt(Math.abs(delta),2)} dB de margem`,className:'good'};if(delta<=SETTINGS.lossOk)return{label:'Compatível',className:'good'};if(delta<=SETTINGS.lossReview)return{label:'Atenção',className:'attention'};return{label:'Revisar',className:'critical'}}
function buildReport(){
 calculate();
 const r=current,tx=modelById(r.txId),rx=modelById(r.rxId),m=r.measurements,e=r.expected,me=r.measured,s=r.supportedChannels,ab=fiberReportState(me.actualLoss,me.lossDelta),ba=fiberReportState(me.actualLossBA,me.lossDeltaBA),statusClassName=r.status==='OK'?'ok':r.status==='Atenção'?'attention':r.status==='Revisar'?'review':'pending';
 const measurement=v=>v==null?'Não informado':`${fmt(v,2,true)} dBm`,gain=v=>v==null?'Não calculado':`${fmt(v,2)} dB`;
 const issues=r.issues?.length?r.issues.map(i=>`<article class="report-diagnostic ${i.level}"><strong>${escapeHtml(i.title)}</strong><p>${escapeHtml(i.detail)}</p><small><b>Ação recomendada:</b> ${escapeHtml(i.action)}</small></article>`).join(''):'<article class="report-diagnostic"><strong>Nenhuma inconsistência identificada</strong><p>Os valores informados estão compatíveis com as referências configuradas.</p></article>';
 $('printReport').innerHTML=`<header class="report-header"><div><h1>DWDM <span>FieldCalc</span></h1><p>Relatório técnico do levantamento do trecho</p></div><div class="report-meta"><strong>${escapeHtml(formatDate(r.surveyDate))}</strong><span>Gerado em ${new Date().toLocaleString('pt-BR')}</span><span>Versão ${escapeHtml(APP_VERSION)}</span></div></header><div class="report-status ${statusClassName}"><strong>${escapeHtml(r.status)}</strong><span>${escapeHtml($('overallStatus').textContent)} · ${escapeHtml($('actionText').textContent)}</span></div>
 <section class="report-section"><h2>1. Identificação do trecho</h2><div class="report-grid"><div class="report-item"><small>Trecho / circuito</small><strong>${escapeHtml(r.span)}</strong></div><div class="report-item"><small>Modo do levantamento</small><strong>${escapeHtml(r.mode)}</strong></div><div class="report-item"><small>Ponto A / origem</small><strong>${escapeHtml(r.origin)}</strong></div><div class="report-item"><small>Ponto B / destino</small><strong>${escapeHtml(r.destination)}</strong></div><div class="report-item"><small>Distância</small><strong>${fmt(r.distance,2)} km</strong></div><div class="report-item"><small>Canais</small><strong>${r.channels??'—'} ativos de 40</strong></div></div></section>
 <section class="report-section"><h2>2. Equipamentos e referências</h2><table class="report-table"><thead><tr><th>Função</th><th>Modelo</th><th>Pout ref. 40 canais</th><th>Faixa operacional</th><th>Alvo ajustado</th></tr></thead><tbody><tr><td>Booster / TX · Ponto A</td><td>${escapeHtml(r.tx)}</td><td>${fmt(tx?.pout,1,true)} dBm</td><td>${fmt(tx?.gmin)} a ${fmt(tx?.gmax)} dB</td><td>${fmt(e.txOut,2,true)} dBm</td></tr><tr><td>Pré / RX · Ponto B</td><td>${escapeHtml(r.rx)}</td><td>${fmt(rx?.pout,1,true)} dBm</td><td>${fmt(rx?.gmin)} a ${fmt(rx?.gmax)} dB</td><td>${fmt(e.rxOut,2,true)} dBm</td></tr></tbody></table></section>
 <section class="report-section"><h2>3. Medições de campo</h2><table class="report-table"><thead><tr><th>Local</th><th>DATA IN</th><th>RX IN</th><th>TX OUT</th><th>DATA OUT</th></tr></thead><tbody><tr><td>${escapeHtml(r.origin)} · Ponto A</td><td>${measurement(m.dataInA)}</td><td>${measurement(m.rxInA)}</td><td>${measurement(m.lineOutA)}</td><td>—</td></tr><tr><td>${escapeHtml(r.destination)} · Ponto B</td><td>—</td><td>${measurement(m.lineInB)}</td><td>${measurement(m.txOutB)}</td><td>${measurement(m.dataOutB)}</td></tr></tbody></table></section>
 <section class="report-section"><h2>4. Atenuação da fibra nos dois sentidos</h2><table class="report-table"><thead><tr><th>Sentido</th><th>Esperada</th><th>Medida</th><th>Diferença</th><th>Efetiva</th><th>Classificação</th></tr></thead><tbody><tr><td>${escapeHtml(r.origin)} → ${escapeHtml(r.destination)}</td><td>${fmt(e.loss,2)} dB</td><td>${gain(me.actualLoss)}</td><td>${me.lossDelta==null?'—':`${fmt(me.lossDelta,2,true)} dB`}</td><td>${me.effectiveAtt==null?'—':`${fmt(me.effectiveAtt,3)} dB/km`}</td><td class="${ab.className}">${escapeHtml(ab.label)}</td></tr><tr><td>${escapeHtml(r.destination)} → ${escapeHtml(r.origin)}</td><td>${fmt(e.loss,2)} dB</td><td>${gain(me.actualLossBA)}</td><td>${me.lossDeltaBA==null?'—':`${fmt(me.lossDeltaBA,2,true)} dB`}</td><td>${me.effectiveAttBA==null?'—':`${fmt(me.effectiveAttBA,3)} dB/km`}</td><td class="${ba.className}">${escapeHtml(ba.label)}</td></tr></tbody></table></section>
 <section class="report-section"><h2>5. Ganhos, potência por canal e capacidade</h2><table class="report-table"><thead><tr><th>Estágio</th><th>Ganho permitido</th><th>Ganho medido</th><th>Potência/canal medida</th><th>Canais estimados</th></tr></thead><tbody><tr><td>TX · ${escapeHtml(r.origin)}</td><td>${fmt(tx?.gmin)} a ${fmt(tx?.gmax)} dB</td><td>${gain(me.actualTxGain)}</td><td>${measurement(me.txPerChannel)}</td><td>${s.tx==null?'—':`${s.tx} de 40`}</td></tr><tr><td>RX · ${escapeHtml(r.destination)}</td><td>${fmt(rx?.gmin)} a ${fmt(rx?.gmax)} dB</td><td>${gain(me.actualRxGain)}</td><td>${measurement(me.rxPerChannel)}</td><td>${s.rx==null?'—':`${s.rx} de 40`}</td></tr><tr><td colspan="4"><b>Capacidade estimada do trecho</b></td><td><b>${s.span==null?'Não calculada':`${s.span} de 40 canais`}</b></td></tr></tbody></table></section>
 <section class="report-section"><h2>6. Diagnóstico e ações recomendadas</h2><div class="report-diagnostics">${issues}</div></section><div class="report-signature"><div>Técnico responsável</div><div>Validação / aceite</div></div><footer class="report-footer">Cálculos baseados na Planilha Padtec V1.2 e no Manual TM.LP64.2023.02.POR.V1. Referência simplificada da fibra: 0,30 dB/km. Este relatório não substitui OTDR, OSNR, análise de reflexão, tilt, dispersão ou avaliação individual dos canais.</footer>`;
 $('printReport').setAttribute('aria-hidden','false');const originalTitle=document.title,datePart=r.surveyDate?formatDate(r.surveyDate).replaceAll('/','-'):todayLocal().split('-').reverse().join('-');document.title=`Relatorio_DWDM_${filenamePart(r.span)}_${datePart}`;const restoreTitle=()=>{document.title=originalTitle};window.addEventListener('afterprint',restoreTitle,{once:true});window.print();
}
function download(name,type,content){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function exportCsv(){const rows=history();if(!rows.length)return;const headers=['Data','Modo','Trecho','Ponto A','Ponto B','Canais','Distância km','TX','RX','DATA IN A dBm','RX IN A dBm','TX OUT A dBm','RX IN B dBm','TX OUT B dBm','DATA OUT B dBm','Perda fibra ref. dB','Perda A→B dB','Diferença A→B dB','Atenuação A→B dB/km','Perda B→A dB','Diferença B→A dB','Atenuação B→A dB/km','Ganho TX dB','Ganho RX dB','Potência média/canal TX dBm','Potência média/canal RX dBm','Canais estimados TX','Canais estimados RX','Canais estimados trecho','Status','Versão'];const data=rows.map(r=>[new Date(r.date).toLocaleString('pt-BR'),r.mode,r.span,r.origin,r.destination,r.channels,fmt(r.distance,2),r.tx,r.rx,fmt(r.measurements?.dataInA,2),fmt(r.measurements?.rxInA,2),fmt(r.measurements?.lineOutA,2),fmt(r.measurements?.lineInB,2),fmt(r.measurements?.txOutB,2),fmt(r.measurements?.dataOutB,2),fmt(r.expected?.loss,2),fmt(r.measured?.actualLoss,2),fmt(r.measured?.lossDelta,2),fmt(r.measured?.effectiveAtt,3),fmt(r.measured?.actualLossBA,2),fmt(r.measured?.lossDeltaBA,2),fmt(r.measured?.effectiveAttBA,3),fmt(r.measured?.actualTxGain,2),fmt(r.measured?.actualRxGain,2),fmt(r.measured?.txPerChannel,2),fmt(r.measured?.rxPerChannel,2),r.supportedChannels?.tx??'',r.supportedChannels?.rx??'',r.supportedChannels?.span??'',r.status,r.appVersion]);download('historico-dwdm-fieldcalc.csv','text/csv',`\ufeff${[headers,...data].map(row=>row.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';')).join('\n')}`)}
function exportJson(){download('backup-dwdm-fieldcalc.json','application/json',JSON.stringify({schema:2,appVersion:APP_VERSION,exportedAt:new Date().toISOString(),records:history()},null,2))}
function importJson(file){const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(reader.result),records=Array.isArray(parsed)?parsed:parsed.records;if(!Array.isArray(records)||!records.every(r=>r.schema===2))throw Error();store([...records,...history()]);renderHistory();$('historyFeedback').textContent=`${records.length} registro(s) importado(s).`}catch{$('historyFeedback').textContent='Arquivo inválido ou incompatível com esta versão.'}};reader.readAsText(file)}
fillModels();$('reportDate').value=todayLocal();document.querySelectorAll('input,select').forEach(el=>el.addEventListener('input',calculate));document.querySelectorAll('.mode button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.mode button').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;calculate()}));$('saveBtn').addEventListener('click',save);$('exportBtn').addEventListener('click',exportCsv);$('backupBtn').addEventListener('click',exportJson);$('importBtn').addEventListener('click',()=>$('importFile').click());$('importFile').addEventListener('change',e=>{if(e.target.files[0])importJson(e.target.files[0]);e.target.value=''});$('printBtn').addEventListener('click',buildReport);$('historyTable').addEventListener('click',e=>{const b=e.target.closest('button[data-action]');if(!b)return;const rows=history(),i=+b.dataset.index;if(b.dataset.action==='delete'){if(confirm('Excluir esta análise do histórico local?')){rows.splice(i,1);store(rows);renderHistory()}}else loadRecord(rows[i],b.dataset.action==='reverse')});$('calculator').addEventListener('reset',()=>setTimeout(()=>{['mDataIn','mRxInA','mLineOut','mLineIn','mTxOutB','mDataOut'].forEach(id=>$(id).value='');calculate()},0));$('appVersion').textContent=APP_VERSION;calculate();renderHistory();
